on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build-windows:
    name: build on windwos
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: build
        run: cargo build --release --package client --package server
      - name: upload server
        uses: actions/upload-artifact@v2
        with:
          path: target/release/server.exe
          name: server.exe
      - name: upload client
        uses: actions/upload-artifact@v2
        with:
          path: target/release/client.exe
          name: client.exe

  build-linux:
    name: build on linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: build
        run: cargo build --release --package client --package server
      - name: upload server
        uses: actions/upload-artifact@v2
        with:
          path: target/release/server.exe
          name: server
      - name: upload client
        uses: actions/upload-artifact@v2
        with:
          path: target/release/client.exe
          name: client
